FROM python:3.9

WORKDIR /app
COPY ./backend/requirements.txt ./requirements.txt
RUN python -m pip install --upgrade pip -i http://mirrors.aliyun.com/pypi/simple/
RUN pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install gunicorn gevent -i https://pypi.tuna.tsinghua.edu.cn/simple
COPY ./backend/ .
COPY ./.env /app/.env
