version: "3"
services:
  backend:
    container_name: backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8001:8001"
    expose:
      - "27017"
    command: 
      - sh
      - -c
      - |
        mongod --dbpath /var/lib/mongo --logpath /var/log/mongodb/mongod.log --fork
        flask run -h 0.0.0.0 -p 8001
    volumes:
      - /var/lib/mongo:/var/lib/mongo


  frontend:
    container_name: frontend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
