version: "3"
services:
  backend:
    container_name: backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.backend
    # ports:
    #   - "5000:5000"
    expose:
      - "5000"
    command: >
      bash -c
      "gunicorn -k gevent -w 1 app:app -b :5000"
    
    # command: >
    #   bash -c
    #   "flask run -h 0.0.0.0 -p 5000"
    networks:
      - db_network
      - web_network
    depends_on:
      - database

  database:
    container_name: database
    restart: always
    image: mongo:4.0
    expose:
      - "27017"
   # port:
   #   - "27017:27017"
    volumes:
      - /var/lib/mongo:/data/db
    networks:
      - db_network

  frontend:
    container_name: frontend
    restart: always

    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    networks:
      - web_network
    depends_on:
      - backend

networks:
  web_network:
    driver: bridge
  db_network:
    driver: bridge